"""initial_schema

Revision ID: 319354c1968f
Revises: 
Create Date: 2026-10-01 11:53:08.137573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '319354c1968f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_invoices')
    op.alter_column('categories', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # First, update existing data to match enum values
    op.execute("UPDATE customers SET customer_type = 'RETAIL' WHERE customer_type = 'Retail Customer'")
    op.execute("UPDATE customers SET customer_type = 'WHOLESALE' WHERE customer_type = 'Wholesale Customer'")
    op.execute("UPDATE customers SET customer_type = 'RETAIL' WHERE customer_type NOT IN ('RETAIL', 'STUDENT', 'TEACHER', 'SCHOOL', 'NURSERY', 'SPEECH_THERAPY', 'WHOLESALE', 'SUPER_WHOLESALE', 'VIP')")

    # Drop existing default to avoid casting errors on the default value
    op.alter_column('customers', 'customer_type', server_default=None)

    op.alter_column('customers', 'customer_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RETAIL', 'STUDENT', 'TEACHER', 'SCHOOL', 'NURSERY', 'SPEECH_THERAPY', 'WHOLESALE', 'SUPER_WHOLESALE', 'VIP', name='customertypeenum'),
               existing_nullable=False,
               postgresql_using="customer_type::customertypeenum",
               server_default='RETAIL')
    op.alter_column('customers', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('customers', 'favorite_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('ix_customers_whatsapp_number'), 'customers', ['whatsapp_number'], unique=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'is_bundle',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('subcategories', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subcategories', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'is_bundle',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_customers_whatsapp_number'), table_name='customers')
    op.alter_column('customers', 'favorite_categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('customers', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('customers', 'customer_type',
               existing_type=sa.Enum('RETAIL', 'STUDENT', 'TEACHER', 'SCHOOL', 'NURSERY', 'SPEECH_THERAPY', 'WHOLESALE', 'SUPER_WHOLESALE', 'VIP', name='customertypeenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'Retail Customer'::character varying"))
    op.alter_column('categories', 'name_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('supplier_invoices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invoice_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('supplier_invoices_supplier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_invoices_pkey'))
    )
    # ### end Alembic commands ###
